#!/usr/bin/env node

console.log('🧪 Laboratory Tools CLI')
console.log('========================')
console.log()
console.log('Available commands:')
console.log('  npm run server       - Start the proxy server (forward or reverse)')
console.log('  npm run lis          - Start the LIS simulator (interactive)')
console.log('  npm run equipment    - Start the equipment simulator')
console.log('  npm run connection   - Start the connection simulator')
console.log('  npm run help         - Show this help message')
console.log()
console.log('Environment Configuration:')
console.log('  IS_REVERSE_PROXY     - Set to true for reverse proxy mode')
console.log('  IS_FORWARD_PROXY     - Set to true for forward proxy mode')
console.log('  PORT                 - Server port (default: 3000)')
console.log('  EQUIPMENT_PORT       - Equipment simulation port (default: 9000)')
console.log('  EQUIPMENT_HOST       - Equipment host (default: localhost)')
console.log('  LIS_PORT             - LIS port (default: 8080)')
console.log('  LIS_HOST             - LIS host (default: localhost)')
console.log()
console.log('Workflow Examples:')
console.log('  # 1. Start reverse proxy server')
console.log('  IS_REVERSE_PROXY=true npm run server')
console.log()
console.log('  # 2. In another terminal, start equipment simulator')
console.log('  npm run equipment')
console.log()
console.log('  # 3. In another terminal, start connection simulator')
console.log('  npm run connection')
console.log()
console.log('  # 4. In another terminal, start LIS simulator for testing')
console.log('  npm run lis')
console.log()
console.log('Forward Proxy Example:')
console.log('  # Start forward proxy')
console.log('  IS_FORWARD_PROXY=true npm run server')
console.log()
console.log('  # Connect LIS simulator directly')
console.log('  npm run lis')
console.log()
